### ISSUE TITLE
Unable to Invoke Mutation - GraphQLParser.Exceptions.GraphQLSyntaxErrorException

### ISSUE THREAD

**Issue by theit8514** [rubrikinc/rubrik-powershell-sdk#144]
Using a mutation's .Invoke() method or calling Invoke-Rsc results in a GraphQLSyntaxErrorException.

Setup
```
> $mutation = New-RscMutationMisc -Operation CreateLegalHold
> $mutation.Var.input = @{
    snapshotIds = @(
            $snap.id
    )
    holdConfig = @{
            shouldHoldInPlace = $true
    }
    userNote = "Hold by request of Client 10/11/2024"
}
> $mutation.Info()

Name            Type                 Description
----            ----                 -----------
API Domain                           Misc
API Operation                        CreateLegalHold
GQL Field                            createLegalHold
Invocation                           $query = New-RscMutation -GqlMutation createLegalHold
Var.input       CreateLegalHoldInput CreateLegalHoldInput!: https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/createlegalholdinput.doc.html
Field           CreateLegalHoldReply https://rubrikinc.github.io/rubrik-api-documentation/schema/reference/createlegalholdreply.doc.html
All Fields                           $query.AllFields()
Selected Fields                      $query.SelectedFields()
Example                              $query.Example()

> $mutation.Example()
$query = New-RscMutation -GqlMutation createLegalHold
# REQUIRED
$query.Var.input = @{
        # OPTIONAL
        snapshotIds = @(
                $someString
        )
        # OPTIONAL
        holdConfig = @{
                # OPTIONAL
                shouldHoldInPlace = $someBoolean     
        }
        # OPTIONAL
        userNote = $someString
}
$result = Invoke-Rsc $query
```

The Example() call shows that I should be using New-RscMutation and the -GqlMutation parameter, but these also don't work.

Using either $mutation.Invoke() or $mutation | Invoke-Rsc generates the following error:
```
MethodInvocationException: Exception calling "Invoke" with "0" argument(s): "
One or more errors occurred. (Could not parse query:

mutation MutationCreateLegalHold($input: CreateLegalHoldInput!)
{
  createLegalHold
  (
  input: $input
  )
  {
  }
}


GraphQLParser.Exceptions.GraphQLSyntaxErrorException: Syntax Error GraphQL (8:3) Expected Name, found }; for more information see http://spec.graphql.org/October2021/#Field
7:   {
8:   }
     ^
9: }

   at GraphQLParser.ParserContext.Throw_From_Expect(TokenKind kind, String description) in /_/src/GraphQLParser/ParserContext.cs:line 194
   at GraphQLParser.ParserContext.ParseField() in /_/src/GraphQLParser/ParserContext.Parse.cs:line 506
   at GraphQLParser.ParserContext.ParseSelectionSet() in /_/src/GraphQLParser/ParserContext.Parse.cs:line 1233
   at GraphQLParser.ParserContext.ParseField() in /_/src/GraphQLParser/ParserContext.Parse.cs:line 555
   at GraphQLParser.ParserContext.ParseOperationDefinition() in /_/src/GraphQLParser/ParserContext.Parse.cs:line 1066
   at GraphQLParser.ParserContext.ParseNamedDefinition(String[] oneOf) in /_/src/GraphQLParser/ParserContext.Parse.cs:line 865
   at GraphQLParser.Parser.Parse[T](ROM source, ParserOptions options) in /_/src/GraphQLParser/Parser.cs:line 40
   at RubrikSecurityCloud.NetSDK.Client.RscGraphQLClient.InvokeGenericCallAsync[T](GraphQLRequest request, OperationVariableSet variables, IRscLogger logger, Dictionary`2 metricsTags) in C:\Users\Administrator\Desktop\src\rubrikinc\rubrik-powershell-sdk\RubrikSecurityCloud\RubrikSecurityCloud.Client\RscGraphQLClientGenericCall.cs:line 124)
Could not parse query:

mutation MutationCreateLegalHold($input: CreateLegalHoldInput!)
{
  createLegalHold
  (
  input: $input
  )
  {
  }
}


GraphQLParser.Exceptions.GraphQLSyntaxErrorException: Syntax Error GraphQL (8:3) Expected Name, found }; for more information see http://spec.graphql.org/October2021/#Field
7:   {
8:   }
     ^
9: }

   at GraphQLParser.ParserContext.Throw_From_Expect(TokenKind kind, String description) in /_/src/GraphQLParser/ParserContext.cs:line 194
   at GraphQLParser.ParserContext.ParseField() in /_/src/GraphQLParser/ParserContext.Parse.cs:line 506
   at GraphQLParser.ParserContext.ParseSelectionSet() in /_/src/GraphQLParser/ParserContext.Parse.cs:line 1233
   at GraphQLParser.ParserContext.ParseField() in /_/src/GraphQLParser/ParserContext.Parse.cs:line 555
   at GraphQLParser.ParserContext.ParseOperationDefinition() in /_/src/GraphQLParser/ParserContext.Parse.cs:line 1066
   at GraphQLParser.ParserContext.ParseNamedDefinition(String[] oneOf) in /_/src/GraphQLParser/ParserContext.Parse.cs:line 865
   at GraphQLParser.Parser.Parse[T](ROM source, ParserOptions options) in /_/src/GraphQLParser/Parser.cs:line 40
   at RubrikSecurityCloud.NetSDK.Client.RscGraphQLClient.InvokeGenericCallAsync[T](GraphQLRequest request, OperationVariableSet variables, IRscLogger logger, Dictionary`2 metricsTags) in C:\Users\Administrator\Desktop\src\rubrikinc\rubrik-powershell-sdk\RubrikSecurityCloud\RubrikSecurityCloud.Client\RscGraphQLClientGenericCall.cs:line 124"
```

**Comment by jakerobinson** [comment]
This is a GraphQL error that occurs when no fields are selected to be returned. Most queries in the SDK have a default set of fields selected, but in this case for `createLegalHold` we don't have any.

Here's a snippet of code you can use that will soon be a part of a new cmdlet called `New-RscLegalHold`

```PowerShell
$snapshotId = "21dc76da-6412-53ac-a1fe-c5a1236b66c"

$query = New-RscMutation -GqlMutation createLegalHold

# Instead of a hash, I prefer to use the built-in .NET types for the input/vars
$query.var.input = New-Object -TypeName RubrikSecurityCloud.Types.CreateLegalHoldInput
$query.var.input.HoldConfig = New-Object -TypeName RubrikSecurityCloud.Types.LegalHoldDownloadConfigInput
$query.var.input.HoldConfig = New-Object -TypeName RubrikSecurityCloud.Types.HoldConfig
$query.var.input.HoldConfig.ShouldHoldInPlace = $true
$query.var.input.snapshotIds = @($snapshotId)
$query.var.input.UserNote = "Hold by request of Client 10/11/2024"

# This is where we set the fields to be returned. Note that "FETCH" here is just a placeholder value. The word itself has no magical powers.
$query.field.SnapshotIds = "FETCH" 

$result = Invoke-Rsc $query
```
